"""Linux: systemd --user timers.

Per task: clockmaster.<task>.service (Type=oneshot, runs `_exec <task>`) and
clockmaster.<task>.timer (OnCalendar, Persistent=true = a start missed while the
machine was off runs once at the next boot/login, like launchd's coalesced
catch-up). OnCalendar ANDs weekday and date, exactly the cron semantics this
tool promises. Times are the user manager's local timezone (the system zone
unless TZ is set in the manager's environment).

Drift = unit file bytes differ from what we would write, or the timer is not
enabled+active. The UI unit clockmaster-ui.service is outside the task prefix,
so the orphan sweep never touches it.
"""
import os
import shlex
import subprocess
import sys
import time
from pathlib import Path

import cron
import identity
from errors import Conflict

name = "systemd"
label = "SYSTEMD"
TIMEOUT = 30


def unit_dir():
    base = os.environ.get("XDG_CONFIG_HOME") or str(identity.home() / ".config")
    return Path(base) / "systemd" / "user"


def unit(task_name, kind):
    return f"{identity.UNIT_PREFIX}{task_name}.{kind}"


def io_log(task_name):
    return identity.data_dir() / "scheduler-io" / f"{task_name}.log"


RUN_USER = "/run/user"  # tests point it at a temp dir


def user_bus_env():
    """Env for `systemctl --user`. A process started outside a login session (a system
    unit, cron, sudo -u) lacks XDG_RUNTIME_DIR/DBUS_SESSION_BUS_ADDRESS, yet the user
    manager may run (linger). Fill them from /run/user/<uid>/bus when that socket exists,
    as `--machine=<user>@.host --user` would; otherwise leave the env as is."""
    env = dict(os.environ)
    if env.get("XDG_RUNTIME_DIR") and env.get("DBUS_SESSION_BUS_ADDRESS"):
        return env
    runtime = env.get("XDG_RUNTIME_DIR") or f"{RUN_USER}/{os.getuid()}"
    bus = Path(runtime) / "bus"
    if not bus.exists():
        return env
    env.setdefault("XDG_RUNTIME_DIR", runtime)
    if not env.get("DBUS_SESSION_BUS_ADDRESS"):
        env["DBUS_SESSION_BUS_ADDRESS"] = f"unix:path={bus}"
    return env


def systemctl(*args, check=False):
    try:
        r = subprocess.run(["systemctl", "--user", *args], capture_output=True, text=True,
                           errors="replace", timeout=TIMEOUT, env=user_bus_env())
    except FileNotFoundError:
        raise Conflict("systemctl not found — this Linux has no systemd; schedule with cron instead "
                       "(see references/systemd.md)")
    except subprocess.TimeoutExpired:
        raise Conflict(f"systemctl --user {' '.join(args)} timed out after {TIMEOUT}s")
    if check and r.returncode:
        raise Conflict(f"systemctl --user {' '.join(args)} failed: {(r.stderr or r.stdout).strip()}")
    return r


def bus_error():
    """None when the user manager answers, else its error text."""
    try:
        r = systemctl("show-environment")
    except Conflict as e:
        return e.msg
    if r.returncode == 0:
        return None
    return (r.stderr or r.stdout).strip() or f"exit {r.returncode}"


# ---------- unit text ----------

def _arg(s):
    """One ExecStart word: double-quoted, C escapes, % and $ doubled."""
    s = str(s).replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%").replace("$", "$$")
    return f'"{s}"'


def _path_ok(p):
    return not any(c.isspace() for c in str(p))


def _output(path):
    if not _path_ok(path):
        return []  # append: takes no quoting — the journal keeps it instead
    return [f"StandardOutput=append:{path}", f"StandardError=append:{path}"]


HEAD = f"# Generated by {identity.APP} — edit the task yaml and run `{identity.APP} sync`, not this file.\n"


def service_text(task):
    lines = [HEAD.rstrip("\n"), "[Unit]", f"Description={identity.APP} task {task.name}", "",
             "[Service]", "Type=oneshot",
             "ExecStart=" + " ".join(_arg(a) for a in (sys.executable, identity.ENTRY, "_exec", task.name)),
             "TimeoutStartSec=infinity", *_output(io_log(task.name))]
    env = os.environ.get(identity.ENV_HOME)
    if env:  # only an explicit override travels; the default is never baked in
        lines.append(f"Environment={_arg(identity.ENV_HOME + '=' + env)}")
    return "\n".join(lines) + "\n"


def timer_text(task):
    return "\n".join([
        HEAD.rstrip("\n"), "[Unit]", f"Description={identity.APP} schedule for {task.name}: {task.schedule}", "",
        "[Timer]", f"OnCalendar={cron.oncalendar(task.cron)}", f"Persistent={str(task.catchup).lower()}", "AccuracySec=1s",
        f"Unit={unit(task.name, 'service')}", "",
        "[Install]", "WantedBy=timers.target"]) + "\n"


def files(task):
    d = unit_dir()
    return {d / unit(task.name, "service"): service_text(task), d / unit(task.name, "timer"): timer_text(task)}


# ---------- state ----------

def _read(p):
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return None


def _query(verb, units):
    """`is-enabled` / `is-active` for many units in one call -> {unit: word}."""
    if not units:
        return {}
    out = systemctl(verb, *units).stdout.split()
    return dict(zip(units, out + ["unknown"] * (len(units) - len(out))))


def registered(task_name):
    return (unit_dir() / unit(task_name, "timer")).exists()


def registered_names():
    d, pre, suf = unit_dir(), identity.UNIT_PREFIX, ".timer"
    if not d.is_dir():
        return []
    return sorted(p.name[len(pre):-len(suf)] for p in d.glob(f"{pre}*{suf}"))


def states(tasks):
    out, live = {}, []
    for t in tasks:
        want = files(t)
        have = {p: _read(p) for p in want}
        if not t.enabled:
            out[t.name] = "stale" if any(v is not None for v in have.values()) else "off"
        elif all(v is None for v in have.values()):
            out[t.name] = "missing"
        elif have != want:
            out[t.name] = "stale"
        else:
            live.append(t.name)
    if live:
        timers = [unit(n, "timer") for n in live]
        try:
            en, ac = _query("is-enabled", timers), _query("is-active", timers)
        except Conflict:
            en = ac = {}
        for n, tu in zip(live, timers):
            out[n] = "ok" if en.get(tu) == "enabled" and ac.get(tu) == "active" else "unloaded"
    return out


def state(task):
    return states([task])[task.name]


# ---------- changes ----------

def _need_bus():
    err = bus_error()
    if err:
        raise Conflict(f"cannot reach the systemd user manager ({err}). " + no_bus_hint())


def no_bus_hint():
    uid = os.getuid() if hasattr(os, "getuid") else "$UID"
    return (f"Timers need a running `systemd --user`: log in through a normal session (ssh/console), "
            f"or run `loginctl enable-linger {os.environ.get('USER', '$USER')}`; inside sudo/su set "
            f"XDG_RUNTIME_DIR=/run/user/{uid}. Without systemd, add a crontab line per task instead: "
            f"`<cron> {shlex.quote(sys.executable)} {shlex.quote(str(identity.ENTRY))} _exec <task>`.")


def _drop(task_name):
    timer = unit(task_name, "timer")
    systemctl("disable", "--now", timer)  # never stops the .service: a run in flight finishes
    for kind in ("timer", "service"):
        try:
            (unit_dir() / unit(task_name, kind)).unlink()
        except FileNotFoundError:
            pass


def sync(tasks):
    _need_bus()
    d = unit_dir()
    d.mkdir(parents=True, exist_ok=True)
    (identity.data_dir() / "scheduler-io").mkdir(parents=True, exist_ok=True)
    desired = {t.name: t for t in tasks if t.enabled}
    changed, reloaded, lines = [], False, []
    for n, t in sorted(desired.items()):
        want = files(t)
        if any(_read(p) != txt for p, txt in want.items()):
            for p, txt in want.items():
                p.write_text(txt, encoding="utf-8")
            changed.append(n)
    gone = [n for n in registered_names() if n not in desired]
    for n in gone:
        _drop(n)
        lines.append(f"- {n}: removed from systemd")
    for p in sorted(d.glob(f"{identity.UNIT_PREFIX}*.service")):  # a service left without its timer
        n = p.name[len(identity.UNIT_PREFIX):-len(".service")]
        if n not in desired and not (d / unit(n, "timer")).exists():
            p.unlink()
    if changed or gone:
        systemctl("daemon-reload", check=True)
        reloaded = True
    unchanged = 0
    st = states(list(desired.values())) if desired else {}
    for n, t in sorted(desired.items()):
        timer = unit(n, "timer")
        if n in changed:
            systemctl("enable", timer, check=True)
            systemctl("restart", timer, check=True)  # re-arm with the new OnCalendar
            lines.append(f"~ {n}: scheduled '{t.schedule}' ({cron.describe(t.cron)}) -> OnCalendar={cron.oncalendar(t.cron)}")
        elif st.get(n) != "ok":
            if not reloaded:
                systemctl("daemon-reload")
                reloaded = True
            systemctl("enable", "--now", timer, check=True)
            lines.append(f"+ {n}: timer re-enabled")
        else:
            unchanged += 1
    lines.append(f"sync done: {len(desired)} scheduled, {len(lines)} changed, {unchanged} unchanged")
    return lines


def unregister(task_name):
    if not registered(task_name) and not (unit_dir() / unit(task_name, "service")).exists():
        return
    _drop(task_name)
    systemctl("daemon-reload")


def linger():
    """'yes' | 'no' | None (unknown)."""
    user = os.environ.get("USER") or os.environ.get("LOGNAME")
    if not user:
        try:
            import pwd
            user = pwd.getpwuid(os.getuid()).pw_name
        except (ImportError, KeyError):
            return None
    try:
        out = subprocess.run(["loginctl", "show-user", user, "-p", "Linger"], capture_output=True,
                             text=True, timeout=TIMEOUT).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    return out.partition("=")[2] or None


def notes():
    out = []
    err = bus_error()
    if err:
        out.append(f"systemd user manager unreachable ({err}) — nothing can be scheduled. {no_bus_hint()}")
        return out
    if linger() == "no":
        out.append("linger is off: timers fire only while you have a login session; after a reboot nothing "
                   f"runs until you log in. Enable: loginctl enable-linger {os.environ.get('USER', '$USER')}")
    return out


def exec_guard(task, now):
    return True


# ---------- UI autostart: clockmaster-ui.service ----------

def ui_unit_path():
    return unit_dir() / identity.UI_UNIT


def ui_unit_text(port):
    args = [sys.executable, identity.ENTRY, "ui", "--fg"] + (["--port", str(port)] if port != identity.UI_PORT else [])
    lines = [HEAD.rstrip("\n"), "[Unit]", f"Description={identity.APP} web UI", "",
             "[Service]", "ExecStart=" + " ".join(_arg(a) for a in args),
             "Restart=always", "RestartSec=2",
             # only the server is stopped on restart/off: runs it started live on
             "KillMode=process", *_output(identity.data_dir() / "ui.log")]
    env = os.environ.get(identity.ENV_HOME)
    if env:
        lines.append(f"Environment={_arg(identity.ENV_HOME + '=' + env)}")
    lines += ["", "[Install]", "WantedBy=default.target"]
    return "\n".join(lines) + "\n"


def ui_unit_port():
    text = _read(ui_unit_path()) or ""
    for line in text.splitlines():
        if line.startswith("ExecStart=") and '"--port"' in line:
            parts = shlex.split(line[len("ExecStart="):])
            try:
                return int(parts[parts.index("--port") + 1])
            except (ValueError, IndexError):
                pass
    return identity.UI_PORT


def ui_main_pid():
    r = systemctl("show", "-p", "MainPID", "--value", identity.UI_UNIT)
    try:
        pid = int(r.stdout.strip() or 0)
    except ValueError:
        pid = 0
    return pid or None


def ui_autostart_state():
    """None = off; else {port, pid, detail}."""
    if not ui_unit_path().exists():
        return None
    pid = ui_main_pid()
    active = systemctl("is-active", identity.UI_UNIT).stdout.strip()
    return {"port": ui_unit_port(), "pid": pid,
            "detail": f"{identity.UI_UNIT}: {active}" + (f", pid {pid}" if pid else "")}


def ui_autostart_on(port):
    _need_bus()
    ui_unit_path().parent.mkdir(parents=True, exist_ok=True)
    identity.data_dir().mkdir(parents=True, exist_ok=True)
    ui_unit_path().write_text(ui_unit_text(port), encoding="utf-8")
    systemctl("daemon-reload", check=True)
    systemctl("enable", identity.UI_UNIT, check=True)
    systemctl("restart", identity.UI_UNIT, check=True)


def ui_autostart_off():
    systemctl("disable", "--now", identity.UI_UNIT)
    try:
        ui_unit_path().unlink()
    except FileNotFoundError:
        pass
    systemctl("daemon-reload")


def ui_autostart_restart(port):
    systemctl("restart", identity.UI_UNIT, check=True)


def ui_autostart_stop():
    systemctl("stop", identity.UI_UNIT)
    deadline = time.time() + 5
    while time.time() < deadline and ui_main_pid():
        time.sleep(0.2)


def ui_autostart_hint():
    linger_off = linger() == "no"
    return ("starts with your user manager, restarts if it dies"
            + (" — linger is off, so only while you are logged in" if linger_off else ""))
